version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tutor
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: scheduler
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://tutor:secret@db:5432/scheduler
    ports:
      - "4000:4000"

volumes:
  db_data: {}